language: node_js
node_js:
- '0.12'
- '4'
- '5'
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "XI2JJvC2U/XDavgD52/WlvvOPNBWCGN8iHXFk7dPuBWrCaEfRmRxIqw9w+8ChQIe8fTCNQ5u+9KxDqO1NRASVj3IieOxdbT+oct2lVBBv96tr/8eJ7YdGm+jTzoh+qRegq+8ZSW9lCYP3XAGWktUe8rjhqllX8ovooYaWft9jHY="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
