language: node_js
node_js:
- '0.12'
- '4'
- '5'
- '6'
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  irc:
    channels:
    - secure: XI2JJvC2U/XDavgD52/WlvvOPNBWCGN8iHXFk7dPuBWrCaEfRmRxIqw9w+8ChQIe8fTCNQ5u+9KxDqO1NRASVj3IieOxdbT+oct2lVBBv96tr/8eJ7YdGm+jTzoh+qRegq+8ZSW9lCYP3XAGWktUe8rjhqllX8ovooYaWft9jHY=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  api_key:
    secure: Qw2bq8lVDIfh6GoLvqae0KuGQ98aDqvqxTiahJTcrMr5aBG4LIkydiJac6yVnTXHVFyTgtpTRlnhGX+nalKf7898wE4Bfh2zhtTFZilFRR+iHRYf0R+0J8Otu1/kGlPYLFmicR5yT+oYOmDApaGK65UQD+of016jb3w4FKiLKkI=
  on:
    tags: true
    repo: taskcluster/taskcluster-base
